name: manage-azure-policy-06c91649
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Deploy_-_Configure_Linux_Azure_Monitor_agent_to_enable_Azure_Monitor_assignments_on_Linux_virtual_machines_a4034bc6-ae50-406d-bf76-50f4ee5a7811/**'
#      - 'policies/_Preview_Deploy_-_Configure_Windows_Azure_Monitor_agent_to_enable_Azure_Monitor_assignments_on_Windows_virtual_machines_ca817e41-e85a-4783-bc7f-dc532d36235e/**'
#      - .github/workflows/manage-azure-policy-06c91649.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_06c91649}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Deploy_-_Configure_Linux_Azure_Monitor_agent_to_enable_Azure_Monitor_assignments_on_Linux_virtual_machines_a4034bc6-ae50-406d-bf76-50f4ee5a7811/**
          policies/_Preview_Deploy_-_Configure_Windows_Azure_Monitor_agent_to_enable_Azure_Monitor_assignments_on_Windows_virtual_machines_ca817e41-e85a-4783-bc7f-dc532d36235e/**
